version: '3.8'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./app/frontend:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8000:80"  # Cambié el puerto para que coincida con el puerto por defecto de nginx
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    volumes:
      - ./app/backend:/app
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
