version: '3.8'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./app/frontend:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./app/backend:/app
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
